### ISSUE TITLE
doesn't work reliably in chrome

### ISSUE THREAD

**Issue by horacegrant** [pisi/Reel#106]
in firefox and ie the reel works fine but in chrome it only works sometimes. it seems to be totally random if the reel initializes or not. what could be the reason for this? anyone else with that problem?

**Comment by cindreta** [comment]
yes i have started a post like this some time ago. it works in chrome but if you refresh the page it starts acting weird and sluggish. still no fix as far as i know. if you do a hard refresh it does not have that problem.

**Comment by pisi** [comment]
Having hard time to reproduce. Please provide test case and mention the version of Reel (`$.reel.version`). Both of you ;) jQuery 1.7 I presume?

**Comment by horacegrant** [comment]
i will provide a test case once i have some time.

in the meantime i also noticed problems in other browsers. it seems to be quite random if the reel initializes or not. could it happen because of a slow server? i use jquery.1.5.1.min.js and reel 1.1.4.

and on some pcs my coworkers got this error on ie8:

(translated from german)

message: access denied
line: 28
column: 466
code: 0
URI: ./jquery.reel.js

what could be the reason for this?

**Comment by pisi** [comment]
In [a comment to #104](https://github.com/pisi/Reel/issues/104#issuecomment-4261888) I've been made aware of further unspecified problems with jQuery 1.5.1. Don't know the exact nature of the problems yet. Now, I can only suggest upgrade your jQuery to at least 1.5.2 (the higher the better).

**Comment by pisi** [comment]
@horacegrant Did you by chance make it to the test case for your issue? I'd love to fix it ;)

**Comment by edeleflie** [comment]
I'm getting similar behaviour. But on both Chrome and Safari. Sometimes (about 1/3 of cases) reel does not initiliase, and the hardcoded load-up image remains. Using jQuery 1.7.1, and reel 1.2.

No success in producing a test case ... but I have lots of images: around 700 small gifs, although I'm only loading up every fourth one.

**Comment by pisi** [comment]
@edeleflie I'm very sorry for your troubles. For me this is still mighty strange, because I do my development primarily in Safari and Chrome and it never happened to me during my hundreds of reloads. And since nobody in this ticket has shared their (un)working code for me to try to experience the same thing you are experiencing, it is very hard if not outright impossible for me to asses the actual causes... But honestly, if you speak about 700 images, I'm not sure if it is a sensible and reasonable amount of images for the DOM itself to handle in a timely manner.

Would love to help you more, guys.

**Comment by edeleflie** [comment]
Hi Petr,

thanks for your reply. I do realise that you cant do anything if the
problem is not reproducible. I'm hoping that the original poster might also
comment that he is working with lots of images ... its one possibility for
the behaviour.

That said, I have found a way to predictably reproduce the bug locally.  On
both Safari and Chrome the bug only appears if I hit the refresh button
(particularly if the images are still loading up and spinning). If I just
hit the home icon, then I have not yet encountered the bug once.

On the one hand that means it is unlikely to be too much of a problem for
the end users .... on the other hand, there's something about the refresh
mechanism that is causing the error. Not sure what is different between
refreshing and just going to the page again.

dont know if that helps..

Etienne

On Fri, Aug 24, 2012 at 7:41 PM, Petr Vostřel notifications@github.comwrote:

> @edeleflie https://github.com/edeleflie I'm very sorry for your
> troubles. For me this is still mighty strange, because I do my development
> primarily in Safari and Chrome and it never happened to me during my
> hundreds of reloads. And since nobody in this ticket has shared their
> (un)working code for me to try to experience the same thing you are
> experiencing, it is very hard if not outright impossible for me to asses
> the actual causes... But honestly, if you speak about 700 images, I'm not
> sure if it is a sensible and reasonable amount of images for the DOM itself
> to handle in a timely manner.
> 
> Would love to help you more, guys.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pisi/Reel/issues/106#issuecomment-7996949.

## 

http://etiennedeleflie.net

**Comment by pisi** [comment]
Etienne, if you strip everything else off, is it still problematic? And what happens when it won't start? Is it still loading or not? (You can find out in the Network tab in the Developer tools in the browser. If only I could see your work for myself. I'm sure I'll be able to spot something... If you can not share publicly, you can always in all confidentiality toss a link to **petr at vostrel dot cz**.

**Comment by edeleflie** [comment]
Hi Petr,

I'm working in wordpress, so its kinda hard to isolate the problem.

I'll be publishing the site to a staging server mid next week ... I'll send
you a temporary URL to have a look at.

Note: I'm currently developing locally, I wonder if the images loading
super-fast might have an effect.

Etienne

On Fri, Aug 24, 2012 at 9:52 PM, Petr Vostřel notifications@github.comwrote:

> Etienne, if you strip everything else off, is it still problematic? And
> what happens when it won't start? Is it still loading or not? (You can find
> out in the Network tab in the Developer tools in the browser. If only I
> could see your work for myself. I'm sure I'll be able to spot something...
> If you can not share publicly, you can always in all confidentiality toss a
> link to _petr at vostrel dot cz_.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pisi/Reel/issues/106#issuecomment-7999250.

## 

http://etiennedeleflie.net

**Comment by pisi** [comment]
Yeah, browser definitely have few loading/cache issues when it comes to local files. But I am too developing it mainly locally and have no problems. As long as you don't load files from file:// protocol, you're safe.

I'm kind of starting to suspect Wordpress. Can you by chance cut the Reel portion out and paste it into new project (non-wordpress this time)?

**Comment by edeleflie** [comment]
Petr,

Here's a link to that site I promised (upon refreshing the page, the reel
often does not initiate)

http://101.0.66.145/~serendi1/

You might be right ... might be a Wordpress javascript loading order thing.

Etienne

On Fri, Aug 24, 2012 at 10:08 PM, Petr Vostřel notifications@github.comwrote:

> Yeah, browser definitely have few loading/cache issues when it comes to
> local files. But I am too developing it mainly locally and have no
> problems. As long as you don't load files from file:// protocol, you're
> safe.
> 
> I'm kind of starting to suspect Wordpress. Can you by chance cut the Reel
> portion out and paste it into new project (non-wordpress this time)?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pisi/Reel/issues/106#issuecomment-7999509.

## 

http://etiennedeleflie.net

**Comment by pisi** [comment]
Etienne,

I took a look on the page (lovely btw! so many deliciously looking goodies!), its code and tried to refresh many times in Chrome and in Safari and so far I wasn't successful at reproducing this issue at all. It always loads and initializes perfectly (and it's not even a fresh browser window, but has lots of open tabs in it). Inspection of the code revealed, that you link scripts within the body content, but this shouldn't be a problem too, since you use the jQuery DOM ready structure. Inspection of the network activity also didn't bring any light into it. Loading order looks to spot on.

It really is strange this. It might me worth it to really experimentally isolate Reel (strip everything else out) and see if the issue of yours persists. I'm clearly unable to spot this issue neither in my current version of Chrome (21.0.1180.79) nor in Safari for that matter (5.1.2). Maybe it is purely a Windows issue? Are you on Win?

Also, since you don't employ mouse wheel at all, it might be beneficiary for you to use `wheelable` option and set it to `false`. That way it won't block mouse wheel scrolling of page and users will be able to scroll their way even through the Reel image.

**Comment by edeleflie** [comment]
Hi Petr,

thanks very much for taking the time to have a look. I'm on OSX (10.6.8
Mountain Lion?). I'm heartened by your inability to reproduce the bug, and
I havn't had any reports from users so far ... so I'm going to put it down
to an issue with my local development environment.

I dont have enough time within this project to isolate the code ... but if
the customer complains or has issues, I will have to continue to debug it.

thanks again.

Etienne

> I took a look on the page (lovely btw! so many deliciously looking
> goodies!), its code and tried to refresh many times in Chrome and in Safari
> and so far I wasn't successful at reproducing this issue at all. It always
> loads and initializes perfectly (and it's not even a fresh browser window,
> but has lots of open tabs in it). Inspection of the code revealed, that you
> link scripts within the body content, but this shouldn't be a problem too,
> since you use the jQuery DOM ready structure. Inspection of the network
> activity also didn't bring any light into it. Loading order looks to spot
> on.
> 
> It really is strange this. It might me worth it to really experimentally
> isolate Reel (strip everything else out) and see if the issue of yours
> persists. I'm clearly unable to spot this issue neither in my current
> version of Chrome (21.0.1180.79) nor in Safari for that matter (5.1.2).
> Maybe it is purely a Windows issue? Are you on Win?
> 
> Also, since you don't employ mouse wheel at all, it might be beneficiary
> for you to use wheelable option and set it to false. That way it won't
> block mouse wheel scrolling of page and users will be able to scroll their
> way even through the Reel image.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pisi/Reel/issues/106#issuecomment-8120128.

## 

http://etiennedeleflie.net

**Comment by edeleflie** [comment]
Hi Petr,

I've changed the way the images are loaded up (it is now an array of
images) ... and the images are PNGs.

I'm now encountering that problem about 80% of the time on Safari. I've
noticed that when I use a Safari browser on a machine that has never
visited http://serendipityicecream.com.au before then the JS reel does not
initialise a majority of the time.

Similar results with Chrome.

Can I ask you to try visiting the site again?

Etienne

On Mon, Sep 3, 2012 at 10:52 AM, etienne deleflie edeleflie@gmail.comwrote:

> Hi Petr,
> 
> thanks very much for taking the time to have a look. I'm on OSX (10.6.8
> Mountain Lion?). I'm heartened by your inability to reproduce the bug, and
> I havn't had any reports from users so far ... so I'm going to put it down
> to an issue with my local development environment.
> 
> I dont have enough time within this project to isolate the code ... but if
> the customer complains or has issues, I will have to continue to debug it.
> 
> thanks again.
> 
> Etienne
> 
> I took a look on the page (lovely btw! so many deliciously looking
> 
> > goodies!), its code and tried to refresh many times in Chrome and in Safari
> > and so far I wasn't successful at reproducing this issue at all. It always
> > loads and initializes perfectly (and it's not even a fresh browser window,
> > but has lots of open tabs in it). Inspection of the code revealed, that you
> > link scripts within the body content, but this shouldn't be a problem too,
> > since you use the jQuery DOM ready structure. Inspection of the network
> > activity also didn't bring any light into it. Loading order looks to spot
> > on.
> > 
> > It really is strange this. It might me worth it to really experimentally
> > isolate Reel (strip everything else out) and see if the issue of yours
> > persists. I'm clearly unable to spot this issue neither in my current
> > version of Chrome (21.0.1180.79) nor in Safari for that matter (5.1.2).
> > Maybe it is purely a Windows issue? Are you on Win?
> > 
> > Also, since you don't employ mouse wheel at all, it might be beneficiary
> > for you to use wheelable option and set it to false. That way it won't
> > block mouse wheel scrolling of page and users will be able to scroll their
> > way even through the Reel image.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/pisi/Reel/issues/106#issuecomment-8120128.
> 
> ## 
> 
> http://etiennedeleflie.net

## 

http://etiennedeleflie.net

**Comment by pisi** [comment]
I did visit the site today first with Chrome and then with Safari, both with cleared caches to have it fresh. And it loaded and initialized OK every single time.

Maybe you can try upgrade to jQuery 1.7.2 at least - I find it quite a deal faster than 1.7.1 and it may help. Don't know, mate :( Can't reproduce...

**Comment by edeleflie** [comment]
Hi Petr,

I think you might have visited the site shortly after I fixed the
problem. I suspect it is a Wordpress issue (this might help some of your
other users)

Instead of importing the Javascript reel file within the body of the html
page, I imported it within the head by calling Wordpress' enqueue function.

Then, instead of using the jQuery syntax for initialising reel when the dom
is finished, I used the <body onLoad="...."> syntax. Now reel works
identically in all browsers (except IE6 and 7, which I dont care about).

Unfortunately, I dont have an explanation ... only a solution.

Etienne

On Sat, Sep 15, 2012 at 1:54 AM, Petr Vostřel notifications@github.comwrote:

> I did visit the site today first with Chrome and then with Safari, both
> with cleared caches to have it fresh. And it loaded and initialized OK
> every single time.
> 
> Maybe you can try upgrade to jQuery 1.7.2 at least - I find it quite a
> deal faster than 1.7.1 and it may help. Don't know, mate :( Can't
> reproduce...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pisi/Reel/issues/106#issuecomment-8565861.

## 

http://etiennedeleflie.net

**Comment by madisvain** [comment]
Had the same problem. Solved it with edeleflie suggestion of having a function in body onLoad.

I could not figure this out yet. It worked in Firefox - did not work in Safari and Chrome. Weirdly it worked in chrome when I pushed the back button.

**Comment by ghost** [comment]
@pisi I think the problem is with the speed value when we use an array of images (chrome and safari), because this bug doesn't happen when we use a sprite, try doing this test...

In http://test.vostrel.cz/jquery.reel/example/object-movie-clockwise-sequence/ go to console on chrome/safari and change the speed to 0.1 ... the animation works (slowly, but works), anything bigger than 0.13 and the images are not rendered correctly on chrome/safari or not rendered at all...

But in http://test.vostrel.cz/jquery.reel/example/object-movie-animation-sprite/ you can put any value on speed, and the animation works fine on any browser.

In FF any value works fine on both links.

**Comment by pisi** [comment]
How I wish to experience this issue. The whole thing is being developed primarily in Webkit/Safari and I still can not reproduce..

@jsgusmao Thanks for observations! Let me straighten this a bit. The sequence example has `speed: -0.2` by default, which is "faster" than `0.13`. Does this example exhibit the same issue when not modified from console?

**Comment by ghost** [comment]
Yes, It only works after I change the speed to something lower than 0.13 or -0.13, sometimes starts working only with 0.09...

**Comment by pisi** [comment]
@jsgusmao That is mighty strange. It never done this to me. Might be caused by some extension you may have installed in your Safari. I am running Safari bare without extensions (only one is Broken Box for blocking Flash). Please visit your Safari preferences and on the Extensions tab uncheck enable on all extensions listed. And try again. Does it still do it?

**Comment by ghost** [comment]
Sorry, I've tested the link only in Chrome, the reel  wasn't working in Safari only in <b>my</b> project but 've found the problem, it was a mistype in my code, not activating the reel (and other stuffs) on Safari.

But the issue is happening in Chrome (even if I disable all extensions), I'm with the latest chrome update, running in Mac OS X 10.6.8 and tested in Windows 7 and XP too (same problem)...

Things i've tried:

Preload images before initializing reel (creating with JS new Image(), and appending to html (hidden) with jQuery)
Setting different headers on the response from server
Disabled all extensions (Chrome)

And it only works if I use a sprite, or use a low speed... Unfortunately I can't use sprites, because i'm rendering dynamic pages created by clients, and I receive a set of images from the server to create the reel.

**Comment by pisi** [comment]
Oh, OK. When I'm talking about Webkit I essentially mean all of them - Safari, Chrome and bare Webkit.

Anyway, I am currently running Chrome 23.0.1271.64 on MacOSX 10.6.8 and no matter what I try (reloads, revisits, speeds up to `3` , still can not see it exhibit any glitches. Of course, at `speed: 3` it has a tendency to skip some frames now and then (but doesn't blink or anything), which is natural in such speeds. Speed of 3 Hz makes results in 108 fps, which is really not feasible without GPU acceleration (30% of CPU time is being consumed). Whereas at the default speed of the example (`-0.2`) the CPU load is around 12%.

Can you check your processor's load when the example is running?

**Comment by ghost** [comment]
man,

I really don't know what's happening, I thought that was something with my connection, but it happened at home too, not only at work... and here all PCs and Macs are having the same behaviour...

Speed higher than 0.13 and the reel seems like it's freezed in Chrome... I've noticed one thing, if I change between tabs in chrome, the image change to the active frame on tab change.

And viewing the source code at the inspector, the img src is updating but it's not rendering.

**Comment by pisi** [comment]
That definitely looks like an issue. Too bad, I don't get to see it. It will take a while to debug this way, but what must be, must be. I am very very curious what is doing that!

> **All of you, who have encountered the problem at hand, please, help me unravel this by making some measurements and taking few screenshots.**

Visit http://test.vostrel.cz/jquery.reel/example/object-movie-clockwise-sequence/

Open your Chrome Developer Tools (f.e. by right clicking and choosing "Inspect Element"). First, maximize the window as much as possible, while leaving at least a peak on the example below, so that you can be sure, that the example actually is exhibiting the symptoms during each recording session.

You will then be working on **"Timeline"** and **"Profiles"** panels (step by step instructions follow). Once you are done, you will end up with six screenshots, which you'll send to _petr @ vostrel . cz_ and that should help me to understand, what is going on in there.

Thank you very much, guys! Now the instructions...

### Timeline panel

##### click "Events"
1. click the "record" button on the bottom of the window
2. let it record just a second or two
3. click the record button again to stop recording
4. grab a screenshot

##### next, click "Frames"
1. click record
2. record 5 seconds this time
3. click record to stop
4. grab a screenshot

##### next, click "Memory"
1. click record
2. let it record for 30 seconds
3. click record to stop
4. grab a screenshot

### Profiles panel

##### select "Collect JavaScript CPU Profile"
1. click Start and it will start recording
2. record 30 seconds
3. click Stop
4. view the CPU Profile report (in the left pane)
5. take a screenshot

##### next, select "Collect CSS Selector Profile"
1. click Start
2. record 30 seconds
3. click Stop
4. view the CSS Selector Profile report
5. take a screenshot

##### next, select "Take Heat Snapshot"
1. click Start
2. view the Heap Snapshot from the left pane again
3. take a screenshot

That's it. If you've performed the measurements on another URL than on the one above, please include the URL in the e-mail.

**Comment by aarongurley** [comment]
I've seen this problem on several of my pages and have had a hell of a time reproducing the error consistently.  I think I have it though.  @pisi I'll email you the link to download my working files now.

There are always some misc times where I open the page and it just doesn't load, but this is the only way I can reproduce the errors consistently. Start by creating two pages.

1) First page: contains a link to the second page and a few loading calls to assets

```
<body>
<a href="firstpage.html">Link</a>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="jquery.reel-min.js"></script>
</body>
```

NOTES for first page:
It's important that https: or http: not be used in front of either and that the reel-min.js file be called locally

2) Second page: This page houses the spin (pulled from example files and modified a bit).

```
<body>
    <img id="image" src='drone.png'/>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="jquery.reel-min.js"></script>
    <script>
      $(function(){ // when DOM ready

        $('#image').reel({
          indicator:   5, // For no indicator just remove this line
          cw:          true,
          frame:       32,
          speed:       -0.2,
          velocity:    3,
          brake:       0.2,
          images:      'drone/#####.png|1..179|5'
        });

      });
    </script>
  </body>
```

NOTES for second page:
1) Include the same assets as the page before, and be sure not to use https: or http:
2) The spin needs to be a sequence and NOT a sprite
3) No size should be set on the image tag

The entire set of files should be placed on a server, or run on a local server like MAMP.  Not all of the following steps are always required to reproduce the error, but these seem to produce consistent results.

Steps to recreate:
1) Open Chrome on OSX.
2) Turn off caching in developer panel (not necessarily needed all the time)
3) Clear browsing data
- Clear browsing history
- Clear download history
- Empty the cache
- Delete cookies and other site and plug-in data
- Clear data from hosted apps

4) Open page 1
5) Click the link to goto page two
6) The spin should NOT load on page 2
7) Refreshing now while on page 2 should load the spin

Resolutions:
There seems to be two consistent resolutions that will address this problem.  Both of which are very doable, but don't seem like they should be preventing the spin from loading.

Resolution 1) Add https: or http: to the jquery call to the Google CDN

Resolution 2) Make sure the image tag has a width and height.  This isn't optimal as I prefer to let my images flex in a responsive layout.  There are ways around it, but for the sake of reproducing the error, that's what I've got.

Hope this helps.

**Comment by developerxnz** [comment]
I had similar issues with chrome and safari, where the reel would only work sometimes. I changed code to use $(window).load(function() { ..//init reels in here.

Another options was to make sure to set the width and height of the main image.(http://www.splents.com/2012/jquery-reel-not-working-with-google-chrome/)

IE7/IE8 Required both of these to work.

**Comment by pisi** [comment]
@aarongurley Will have to yet read through your post, but I didn't catch those files and they expired :( My bad. Please resend them. Thanks!

But guys, please **always remember, that both image width AND height are required to be defined** somewhere in order for Reel to work. Be it on the `<img>` tag, in the CSS or with the [`attr`](http://jquery.vostrel.cz/reel#attr) option on the fly, it doesn't matter. But both need to be defined.

**Comment by ghost** [comment]
I have similar issue wit chrome and safari sometimes it initializes and some times nor. I am using jquery 1.7.2 and reel 1.2. You can check it on this page http://justeastern.com/monsoon (click on 360 view icon under large image).

**Comment by pisi** [comment]
@hatimgenius In your case, you do two things wrong:
1. you basically do `$('#popup_360').reel()`, but yours `#popup_360` is a `<div>`. You need to intitialize on your `<img>` like so `$('#product_360').reel()`
2. **your image doesn't have dimensions specified** - you need to set `width` and `height` attributes on the image, otherwise Reel rejects it.

**Comment by renaldas** [comment]
Can confirm, if you set image width and height, chrome issue will go away..

**Comment by pisi** [comment]
Yes, can not stress this enough: **always set both width and height of the image** (doesn't matter if with HTML or CSS)

**Comment by OZZlE** [comment]
I experienced this issue also but only in Safari, worked fine in chrome. I found that this issue ONLY occurred when I merged this javascript together with all other js on the site.

After specified width & height it started working properly again however.. strange issue..

I didn't want to set any width or height in order for my customer to be able to upload any image he/she wanted but now I will solve it instead by measuring the width & height of the initial image in BE..

_Edit_: It probably depends on how fast the images loads and not browser..
