### ISSUE TITLE
Setting vertical `revolution` 

### ISSUE THREAD

**Issue by jheeffer** [pisi/Reel#115]
Hey, I would also add a revolution_y option. I suppose it's just changing row 1172 to

```
      revolution_y= opt.revolution_y || (opt.rows > 3 ? space_y : space_y / (5 - opt.rows)),
```

Cheers,
Jasper

**Comment by pisi** [comment]
I would like to see a use case for such a feature.

**Comment by jheeffer** [comment]
Sure, no problem!

http://jasperheeffer.nl/reel_test/ 

(might need a ctrl+f5 to show, it does in chrome, but I suppose that's a browser bug with big images)

I use this reel in a touch screen application. It fills the whole height of a 22" touch screen. To drag all the way from the top to the bottom of the screen to see the 4 rows is not intuitive or user friendly.
By setting the revolution_y, you can decrease the length of the gesture needed to explore the rows of the object.
We user-tested different revolution_y 's on this application and a lower value (200) was prefered over the default.

**Comment by pisi** [comment]
OK, Jasper, I agree that the default behavior is not very helpful in fullscreen Reel environment. So this is a valid requirement after all! :) We've come around this issue in issue #14, but were able to get away with automatical adjustment without additional options or data value. Not this time i guess..

The solution you proposed would indeed work and would deliver what you need, but would mean one new option and one new data value.

However, let's do it more solid and without introducing new option (there's far too many of them already). The `revolution` option shouldn't be limited to a single number input and it should as an optional alternative accept Object notation containing one or more individual axes. So that you can use revolution values:

``` js
200, // Standard horizontal 200px revolution
{ x: 200 } // Alternative for the numeric input above
{ x: 200, y: 300 }
{ y: 300 }
```

If no value is set for `revolution` or for any of its axes, a default revolution is calculated based on physical dimensions and properties of the stage and setup (this is done already):
- horizontally double the image width or 1/2 of `stitched` option value for stitched panoramas
- vertically the image height for 3 or more rows or a fraction of it for less than three rows

Internally the set/calculated revolutions are stored in data slots `revolution` and `revolution_y`. In the data I opted for two simple numeric values instead of Object to be monitorable.

I sincerely hope this will resolve your problem and will allow you and others to use custom revolution values for vertical axis.
