### ISSUE TITLE
Ios Problem

### ISSUE THREAD

**Issue by sphereoid** [pisi/Reel#12]
I tried to test out my reel on my ipad and discovered a problem where you can see the sprite sheet as you cycle through the images.  It doesn't have this problem on anything else.  It's difficult to describe but for some reason the section of the sprite sheet doesn't take up the entire space allotted to it.  Has anyone had something similar to this happen before?

**Comment by pisi** [comment]
This is an unfortunate known issue in Reel 1.0.x caused by iOS imposed memory limits. Please see [FAQ](https://github.com/pisi/Reel/wiki/FAQ) page which explains this issue and links to official Apple guidelines mentioning the exact limit value.

Reel 1.1 addresses this issue in two ways:
- it fixes the scaling-down of the sprite by enforcing its original dimensions (but that badly affects visual quality of the image).
- it allows to use sequence of individual images (frames) using the `images` option which accepts array of images. That way you'll be safely within the memory limits.

So, if you want to use the sprite there's no other way but to learn to respect the limitation. Or cut your sprite into individual images and use `images` option.
