### ISSUE TITLE
Cross-domain errors in IE

### ISSUE THREAD

**Issue by reformatco** [pisi/Reel#120]
I have used the plugin and works fine on everything, when the page opens in a Lightbox I get the cross-domain warning in Chrome even though I've added crossdomain.xml from h5bp and enabled mod header. 

`Unsafe JavaScript attempt to access frame with URL`

It still works fine in Chrome, Safari and Firefox.

IE however (7-9) simply just has an error

```
SCRIPT 5:
Access is denied
line 28 character 466
```

Which seems to be the following

```
$=h.browser.opera
```

I am sure it has something to do with cross-domain scripting but any help would be much appreciated.

**Comment by pisi** [comment]
It's hard to tell from the error messages only. Can you show me? Or even better replicate your problem in a [fiddle](http://jsfiddle.net/)?

**Comment by reformatco** [comment]
Thanks for getting back @pisi i have tried to replicate the problem at http://jsfiddle.net/W2tYR/3/ by adding iframe content from your Sampler and then a minimal version on my server. Yours is working on IE but mine isn't, I get the same error although this time I am hotlinking through to your script at http://code.vostrel.cz/jquery.reel.js

I am starting to think it might be something you have on your hosted examples that is the difference.

I have tried the following with no luck

php header of `header("Access-Control-Allow-Origin: *");`
apache `Header set Access-Control-Allow-Origin "*"`
h5bp crossdomain.xml

**Comment by pisi** [comment]
Thank you for the fiddle test case - it did help a lot.

There is a difference. Your code uses the latest stable version 1.1.4, which doesn't work well in iframes, whereas the sampler uses the 1.2rc, which has iframe issues fixed and thus works better in a mixed-domain environment. You can tell the version by reading `$.reel.version`. Unfortunately the RC had a flaw in preloading images, which is fixed now in the development version (but not yet released as RC2). Please switch to the [v1.1.4-devel](/pisi/Reel/tree/development) and you should be fine.

My server isn't in any way configured extra for cross-domain, so that wouldn't be it.

**Comment by reformatco** [comment]
I seriously wish i could high fix you man! This has fixed my issue, you are the best!
Do you have a donate button so i can buy you a beer?

**Comment by pisi** [comment]
Thank you, man. Glad it worked for you! There are donations buttons over at http://jquery.vostrel.cz/reel#free Cheers!
