### ISSUE TITLE
Events & Styles applied on reel are lost

### ISSUE THREAD

**Issue by connersau** [pisi/Reel#137]
Hey,

firstly just want to say thank you for this awesome plugin, it works really well and theres great documentation

im building a site that uses the reel, and the reel works perfectly fine, but the issue lies when i move to a new page and then go back to the original page containing the reel, all the reels css and bindings are no longer set.

see this screenshot to hopefully explain the issue - http://conrad.tribalddbmelb.com.au/reel/reel.jpg - screen 1 is the page with the reel working perfectly, screen 2 is a new page that is clicked which is loaded via ajax, and screen 3 is the original page with the reel after the "back" button has been clicked (not the back button in the web browser), which has a full listing of all the image frames (as the display:none style is no longer applied to it) and i can no longer rotate the reel

i suspect its because the css is set inline, is it possible to have the css and events set to the class of the reel and not its id?

also im using Reel v1.2 and jQuery v1.7.2

hopefully that all makes sense!

appreciate any help you can give me!
thanks
conrad

**Comment by pisi** [comment]
Hi Conrad,

does the back button facility remove DOM elements of one page to display another page? If so, you might want to try to [`.unreel()`](http://test.vostrel.cz/jquery.reel/docs/jquery.reel.html#Destruction) the page 1 instance first, if that doesn't help. Also it has to make it `.reel()` again if the new page has Reel in it.

For a more competent answer, I'd have to see your implementation (screenshot helps, but doesn't go all the way) or isolated reproduction of the issue, best as [fiddle](http://jsfiddle.net) if possible.

**Comment by connersau** [comment]
Hi Petr,

The back button facility shouldnt remove the DOM elements, because essentially that page still exists (all elements are on page just not visible - i animate it to the very left out of view), and then animate it right when the back button is clicked.

I was able to apply the CSS styles to the reel by triggering "setup" on the instance (ie. reelInstance.trigger("setup"); )  but i cannot drag/rotate the reel.

Thanks for your response, you can see the site at http://britax.tribalddbmelb.com.au/BRI0004/build/stroller , to see the behaviour go to that page, then click the "Watch the promo video" or "Colours available" button at the bottom, then click "Back" 

ill try to use .reel() and .unreel()

regards,
conrad

**Comment by pisi** [comment]
Conrad,

there must be some kind of additional DOM manipulation happening. When I am looking at the stroller, I use console to retrieve the image node jQuery and store the reference aside:

``` js
comparisonImage = $('#stroller-image');
```

Now when I repeat the jQuery and this time compare it with the stored reference, it indeed positively asserts that the node stored and the one in the DOM currently are the exact same one:

``` js
comparisonImage[0] == $('#stroller-image')[0] // true
```

Now I click on "Colours" and run the very same above comparison and this time it is negative, which pretty much points on the fact, that these are different nodes:

``` js
comparisonImage[0] == $('#stroller-image')[0] // false !!!
```

This is mostly caused by manipulations of DOM using `.html()` with structured input. Such usage doesn't actually reuse the same nodes, but rather replicates them, which means discontinuity.

Another thing I've noticed is that when you get back, the instance really is not started at all also pointing on some non-standard DOM manipulations. You can see currently running instances on page with `$.reel.instances` containing them in a jQuery object.

However as long as the Reel instance doesn't leave the DOM, doesn't pass through some intermediate `.html()` call or anything disruptive to DOM and just moves out of view, you don't need to trigger `teardown` or even call `.unreel()`. In fact in that case you don't need to do anything special at all. No `.reel()` either. Just leave it as is, Reel itself doesn't have any positional concerns. 

Wish I could help you more.
