### ISSUE TITLE
custom cursor troubles

### ISSUE THREAD

**Issue by albell** [pisi/Reel#143]
I'm running into a dense forest of problems trying to customize the cursor on hover and on drag. I'll try to summarize them quickly:

1) There's no js cursor option for the "active" state (while dragging). I would like control over the separate states.

2) The "reel-panning" cursor style is written using a !important declaration in the javascript, making it impossible to override using a conventional stylesheet:

```
.reel-panning,
.reel-panning * {
    cursor: url('http://code.vostrel.cz.jquery.reel-drag-down.cur', move !important;
}
```

3) There are bugs in webkit where `cursor` declarations don't cascade correctly. A lot of these bugs are outstanding for many years, and they don't seem likely to be fixed any time soon. This means that overriding custom cursor declarations is in reality often unworkable, and that you've essentially got to get it right the first time in the code.

4) Your CDN was refusing to serve your "360" cursor file for a day or so, while i was developing. Too many requests? (It's working for me now again.) It's really a lovely cursor, but even if I wanted to use it for my current project I would want to serve it locally, for the sake of stability and control. This is a very minor point, but it might help the next guy if you bundled your ".cur" file in the distribution.

---

As a solution to all of these problems, it might make sense to externalize all the cursor CSS into a couple of declarations that can easily be edited conventionally and directly. Developers could just include them in their stylesheet. Please don't write them into the document where Dev Tools element inspectors can't trace their origins in a conventional fashion. For me personally, it's not convenient, just confusing :)

```
.reel-overlay,
.reel-overlay * {
    cursor: url('http://code.vostrel.cz/jquery.reel-drag.cur'),move;
}

.reel-panning,
.reel-panning * {
    cursor: url('http://code.vostrel.cz/jquery.reel-drag-down.cur'),move;
}
```

People who want to customize the cursor with a grabbing hand, then, for example, could just do this:

```
.reel-overlay,
.reel-overlay * {
cursor: url('images/my-open-hand-cursor'),move;
cursor: -moz-grab;
cursor: -webkit-grab;
cursor: grab; // future proofing
}

 .reel-panning,
.reel-panning * {
cursor: url('images/my-closed-hand-cursor'),move;
cursor: -moz-grabbing;
cursor: -webkit-grabbing;
cursor: grabbing; // future proofing
}
```

Sorry for another long post  :)

**Comment by pisi** [comment]
1. Yes, there's no option for that. You can either use `cursor` option with `"hand"` value, which will give you the grabbing hand with active state. Or you can do this by styles - every time Reel is being panned by any means, the `<html>` element of hosting document will be flagged with `reel-panning` class name.
2. Reel 1.2's mission was to get rid off most of `!important`s and make styling less of a nightmare. Right now, instead of applying styles inline, Reel would first put together a CSS stylesheet and prepend it to the `<head>` (you can inspect it in Firebug or similar tool). This position makes it the bottom stylesheet in the stack, so you can easily override all of its declarations without the need to use `!important` in your style. Only exception is the `.reel-panning` declaration which does still use `!important` (to display the cursor even outside the image while dragging) and needs to be redefined with use of `!important` too. So it's not impossible. Your `!important` will always have priority over Reel's.
3. Well, yeah, browser bugs are a pain. In Opera for example, custom cursors don't work at all...
4. Oh, thanks for the report. Wasn't aware of that. Should be just fine now. Sorry for the inconvenience. You are right about including the files into the release! That's exactly, what I'll do in 1.2.1 - watch issue #144.

The solution basically describes how Reel 1.2 works. Most of the styles are defined in the stylesheet at the beginning of `<head>`. You can easily define your own cursors anywhere in the document. _For example you'd like to have say a hour glass/watch cursor when idle and a pointing hand when panned/dragged:_

``` css
#image{
    cursor: wait;
}
.reel-panning,
.reel-panning *{
    cursor: pointer !important;
}
​
```

Please be aware of caveats. You can not set the style with `.reel-overlay` only, because the generated stylesheets are instance-specific, so they use ID to target the appropriate instance, and as IDs have bigger weight compared to classes, just the class alone is too light. Also be aware, that `.reel-panning` is not a class of the instance, but a class of `<html>` (only when dragged).

Here's a fiddle with the demo: http://jsfiddle.net/WKfGx/

**Comment by pisi** [comment]
Also you can also override the default [`$.reel.cdn`](http://test.vostrel.cz/jquery.reel/docs/jquery.reel.html#Content-Delivery-Network) setting with your own path to folder, where your assets are. So that whenever an image resource is requested, it will use your path.

``` js
$.reel.cdn = 'http://www.myserver.com/';
```

**Comment by albell** [comment]
Petr- thank you for such a thorough and helpful answer.

**Comment by albell** [comment]
Two years later (!), working on another https site with REEL, I'm still dealing with this! The whole CDN idea here basically seems wrong to me. CDNs are great for something like a major library, where a lot of people are linking to the same thing. But if there is a keep-alive connection already to the host server, local assets are plenty fast. Why not just provide the short css files, and tell authors to include them in their stylesheets? Why does the plugin have to prepend its own stylesheet? What if I don't want to be dependent on your CDN? IMHO This is just way too clever.

As far as loading performance, a concatenated CSS file in markup in the head will load sooner than one prepended by a script at the bottom of the body. So your pattern actually incurs a performance penalty!

Lastly, as I noted in my original comment #3, in webkit the cascade still doesn't work correctly for custom cursors. That makes conventional CSS overrides impossible! So I actually have to go in and programmatically remove out the stylesheet the plugin is prepending, and write my own in order to get this to work. Double the trouble...

**Comment by pisi** [comment]
You don't need to be dependent on my CDN or on my cursors at all in fact.

You can either:
- use my cursors from your server by putting content of the [`assets/` folder](/pisi/Reel/tree/master/assets/) on your server and pointing to the folder with `$.reel.cdn = 'http://www.myserver.com/assets/';`
- use your own cursors by replacing the files on that location with your own ones, keeping the filenames
- use your own cursors CSS declaration. You can inspect the injected stylesheet for where cursors are applied.

Also if you're wresting with this idea because of HTTPS issues, there are two more options you can explore:
- there is a HTTPS-enabled CDN over at jsdelivr.net, see issue #249
- my CDN also knows HTTPS but not on my own domain. If you use `$.reel.cdn = "//reeljs.appspot.com";` you should be able to load assets without warnings.

As for the performance concerns, Reel won't initialize usually until the DOM is ready and only then it will inject the stylesheet (which btw. contains quite a bit more than just cursors and will contain even more), so it effectively has no power to cause any performance penalty.

**Comment by albell** [comment]
Thanks. Setting the `.cdn` string does work. But I still think there's a better way.

> "As for the performance concerns, Reel won't initialize usually until the DOM is ready and only then it will inject the stylesheet (which btw. contains quite a bit more than just cursors and will contain even more), so it effectively has no power to cause any performance penalty."

Well.... making CSS load depending on javascript execution most definitely incurs a css-referenced-asset performance penalty, in pretty much all cases. Consider the common scripts-at-bottom-of-the-body pattern:

```
<head>
<link href="main.css" rel="stylesheet">
</head>
<body>
<div class=reel-stuff></div>
<div>my other content</div>
<script src="mylibrary.js"></script>
<script src="reel.js"></script> // appends 'reel.css' to the head
</body>
```

In this case, here's what happens: First the browser's <a href="http://andydavies.me/blog/2013/10/22/how-the-browser-pre-loader-makes-pages-load-faster/">preload scanner</a> puts all page content explicitly referenced with a `src` or an `href` into a load queue, including `main.css`, `mylibrary.js`, and `reel.js`. But the preload scanner can't download `reel.css`, because it can't see it on the page!  The CSSOM gets constructed, and the DOM is constructed. Then once `mylibrary.js` has loaded, it executes. Then once `reel.js` has loaded, and the DOM is ready, `reel.js` executes, and appends the new `reel.css` stylesheet to the head. Then the browser has to go back, and reconstruct the CSSOM a second time. Once the browser sees that the selector(s) in `reel.css` are matched in the DOM, only then will it fire the request for the cursor images. The requests for the cursor images are effectively delayed, because you've made them dependent on javascript execution. The custom cursor doesn't appear until needlessly late. There is a long Flash of Unstyled Cursor™!

Here's a better pattern:

```
<head>
<link href="main.css" rel="stylesheet">
<link href="reel.css" rel="stylesheet">
</head>
<body>
<div class=reel-stuff></div>
<div>my other content</div>
<script src="mylibrary.js"></script>
<script src="reel.js"></script>
</body>
```

In this pattern, the CSSOM only gets built once. CSS Selectors get matched against the DOM once for initial page load. Even if `mylibrary.js` or `reel.js` get delayed on the wire, or take a long time to execute, the custom cursor image can be requested, received and rendered as soon as the `reel-stuff` div is in the DOM. The idea is just to decouple CSS and JS, and take advantage of the browser's native asychronicity. Is there any reason why the different styling contexts for the plugin can't be broken out into different `reel-*` class names in a master stylesheet?

Lastly, perhaps I have been unclear about the problem with overrides in webkit for custom cursors. We seem to be miscommunicating. What I mean is that for

```
.some-element { cursor: url(my-cursor1.png), auto;}
.some-element { cursor: url(my-cursor2.png), auto;
```

The user will often actually see cursor1, and not cursor2 ! The override doesn't apply! This is a webkit bug. It's not a reel bug, per se. But it's something that needs to be worked around. So your advice "just override the declaration in CSS" doesn't work. The custom cursor image path needs to be set correctly the first time :/
