### ISSUE TITLE
Sequence definition out of sync with actual server content

### ISSUE THREAD

**Issue by labmate** [pisi/Reel#153]
Hello!

My problem that it's blinking in every browser.
On localhost  with firefox it's not blinking, but on server it does. 
On the other browsers(IE, Chrome, Opera, Safari) it's blinking indepedently it's on localhost or on server.
What can i do against the blinking? I use 12 frames.

**Comment by pisi** [comment]
Sorry to hear that. Interesting indeed. I'd love to see that. Can you show me?

**Comment by labmate** [comment]
Yes, you can see it here:

---

**Comment by pisi** [comment]
Thanks! But I can not even get your example to rotate :/ If you can please make absolutely sure, that this example is fully functional and exhibits the problem at hand.

However quick inspection of code revealed, that you have only `width` set on the image and not `height`. While this may work, it means additional calculation of each image's height by the browser and may be causing the blinking. It surely is the first thing I would try to add there.

**Comment by labmate** [comment]
I've set the height, but it's still blinking :(

2012/11/6 Petr Vostøel notifications@github.com

**Comment by pisi** [comment]
OK, I see the problem now. You have problem in your files, so no problem with Reel, just a simple URL misconfiguration easily discoverable in network console, where 404 errors pileup. Your files don't really fit the default expectations for three reasons:
1. the sequence starts with **0** whereas the default is 1, and
2. the increment of your sequence is **3** (you have 00000.jpg, 00003.jpg, 00006.jpg, ..., 00030.jpg, 00033.jpg) whereas the default is 1, and
3. you use **12** frames whereas default is 36.

Easiest solution would be stick to the expectations and rename the files to go 00001.jpg, 00002.jpg, 00003.jpg, ..., 00011.jpg, 00012.jpg, that would solve points 1 and 2. Then only add:

``` js
    frames: 12
```

to your options to address point 3 and you're set.

---

You might also want to fix the opposite dragging problem you have there. Either reverse the order of the images when renaming them or use:

``` js
    cw: true
```

to tell Reel, that you have captured the images in clockwise fashion rather than the expected counter-clockwise default. As a rule of thumb, when you drag, the near part of the scene shouldn't go opposite to the drag, but rather follow the drag to get a more direct and natural feel from the interaction.

**Comment by labmate** [comment]
It's working now. Thanks for your help!:)

**Comment by labmate** [comment]
Hello!
I've got one problem. I've noticed that sometimes the reel is not inizialized. If you choose a color on the side, sometimes, wont do anything just changing the picture but you cant rotate it. If you click again on the color that you chose before, it works perfect. Can you help me why is this happening?

**Comment by pisi** [comment]
This second problem really is quite off-topic here in, but since I've already mentioned this solution in this thread, I guess it doesn't matter this time ;)

Reel needs to be given both dimensions and while automatic detection of one or more of them is possible, it is heavily browser-dependent (for example in my Safari, `width` only won't initialize at all). Try complement the `width` parameter of `<img>` width `height`.
