### ISSUE TITLE
Reel's edge not working with IE7-8

### ISSUE THREAD

**Issue by tduppstadt1** [pisi/Reel#159]
I'm very serious about using Reel for a big project which contains all the the base features I am needing which is fantastic. Your website says that it is supported from IE 6+. My target is IE7+. I tested your website on Windows XP IE7 and it was not working. I tried in Win7 64bit  IE8 and it was not working also. 

IE7 Error Line: 24; Object does not support this property or method  (no script source for the error)
IE8 Error Line 23; Object does not support this property or method;  in jquery.reel-edge-bundle.js

I also downloaded your examples and latest JS files from Git in case the examples on the website itself were not running the latest JS but the result from the same.

Also Your website says it supports Android 2.3+. I tested your website in Android 4.0.3 in Dolphin and it also did not work there. (this is more of an FYI but I am looking for mobile support as well).

If there is a working version for IE can you point me to it? 

Thank you for your time... I hoe we can get this resolved cause I am anxious to use your product.

thanks!
Thom

**Comment by tduppstadt1** [comment]
ok... no longer any dev support for a buggy product? take down your site please cause your wasting our time...See ya!!

**Comment by pisi** [comment]
Hello Thom,

I am so sorry I was not able to respond in time. Sadly, my current work assignment keeps me miles away from my beloved open-source baby :/ My apologies.

I just checked everything and ran all tests once again in IE 9 and 8 on Win7 and IE 7 on Win XP. And you are right, that the website is currently not running in IE 8 and below. The reason for that is it's running the _edge_ development version of Reel and not the _stable_ version actually [downloadable on the website](http://jquery.vostrel.cz/reel#download). The edge version sometimes develops issues and this way I can discover them before releasing it as stable.

However, the **current stable version 1.2 is completely functional in IE 7+**. I wish I have a working IE 6 setup to test on, but those days are long gone and the IE6+ compatibility is now purely theoretical. The Android compatibility on the other hand is practical and tested on my 2.3.5.

The [stable code](/pisi/Reel/tree/master) download contains working [examples](http://test.vostrel.cz/jquery.reel/example), which you can try instead of the website. My apologies for the confusion... If you have any more problems, please do contact me here again. I will do my best to respond in more timely manner.

Best,

Petr
