### ISSUE TITLE
no image when speed is 0

### ISSUE THREAD

**Issue by michaelhensel** [pisi/Reel#16]
I like to show just the first image in the sequence and have no auto scroll. When I set speed to 0 or delete it all together, I see no image, until I click in the empty field. The mouse has the "reel" look, but no image is showing. See: 
http://thebuddhashop.net/index.html (scroll = 0.1) visible but rotating
vs
http://thebuddhashop.net/index.htm (scroll = 0) not visible until click

**Comment by michaelhensel** [comment]
I did switch the two files around:
The html is set to 0 (no scroll) - no image visible:(
The htm is set to 0.1

**Comment by pisi** [comment]
Michael,

this is a known bug filed as an [issue 11](https://github.com/pisi/Reel/issues/closed#issue/11). Sorry for inconvenience.

Good news is, that it has already been solved and patched version is available in the [zero-fraction-fix](https://github.com/pisi/Reel/tree/zero-fraction-fix) branch.

Worse news is, that it didn't make it into a patch release just yet. Hopefully I will release it officialy soon.

Otherwise, for current 1.1 a quick workaround is to use `frame` option other than 1.

Please feel free to reopen this issue in case this did not solve it.

.pisi

**Comment by pisi** [comment]
For the record, I [just released](https://github.com/pisi/Reel/issues/closed#issue/11/comment/896575) the patch [version 1.1.1](https://github.com/pisi/Reel/tree/v1.1.1) with a cure for this pain.
