### ISSUE TITLE
How to use development code?

### ISSUE THREAD

**Issue by landrvr1** [pisi/Reel#160]
I took a look at this thread because I cannot get scrollable to work:  

https://github.com/pisi/Reel/issues/149

When I go to the development branch I'm not sure what I"m supposed to do......?  I tried replacing:

jquery.reel-1.2-bundle.js
jquery-1.7.min.js

with

jquery.reel.js
jquery.reel-min.js

but that prevented reel from working at all.  What I'm trying to accomplish is to only have left and right swipe on the iPad actually engage reel, but vertical will allow scrolling.

BTW, been having great fun with Reel.  It's been a pleasure trying things out!

**Comment by landrvr1** [comment]
pisi must be away...anyone checking the Issues that might help me out?  StefanDV, are you around?

**Comment by landrvr1** [comment]
pisi!!!????  lol.  Where did you go?

**Comment by pisi** [comment]
Hi @landrvr1! Reel is a one-man-boat so far, so when it happens and I am consumed by my work commitments, like I've been now, the boat quite literally slows to a stop. But am back again! :)

To use the patched development branch code, you need to [get this `jquery.reel-min.js`](/pisi/Reel/tree/development/jquery.reel-min.js) and replace the `jquery.reel-1.2-bundle.js` with it. And be sure to keep the jQuery 1.7 link in, otherwise there's no ground for Reel at all.
