### ISSUE TITLE
rotate 2 images simultaneously.

### ISSUE THREAD

**Issue by prateeksjoshi** [pisi/Reel#183]
i want to rotate 2 images simultaneously... 
if i rotate 1st image then, 2 image should also rotate in the same manner...

here is my code.

``` js
      $('#image').bind('frameChange', function (e,d,frame) {
          $('#image1').reel({'frame':frame});
      });
```

trying to achieve it by the above way but showing error..

**Comment by pisi** [comment]
What error does it show? Do you have an example I can play with?

**Comment by prateeksjoshi** [comment]
its showing an error 
Uncaught TypeError: Cannot read property 'orbital' of undefined.. do i need to setup orbital property??

i am getting my solution with $('#image1').trigger('frameChange', frame); but in reel 1.2.1 version trigger is depricated and it suggests to modify to it as $('#image1').reel('frame', frame); but then i got the error as mentioned above..

**Comment by pisi** [comment]
You don't need `orbital` property for this (unless of course your setup is "orbital" - two perpendicular orbits). This portion is your problem:

``` js
  $('#image1').reel({'frame': frame});
```

This is incorrect and I didn't notice it the first time. This simply tries to initialize new Reel. In order to control an existing one (the way triggering `frameChange` used to) you need to provide two arguments to `.reel()`. First being the data field name and second the value. Like this:

``` js
  $('#image1').reel('frame', frame);
```

See [Write Access chapter](http://test.vostrel.cz/jquery.reel/docs/jquery.reel.html#Write-Access) in the documentation for more details.
