### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sagarquad** [pisi/Reel#198]
I am using this wonderful plugin  with 68 images with multi row sequence example with 2 rows, and It's working fine,but I want to give 720 images with 2 rows of each 360 images it give error like this: " Maximum call stack size exceeded.". Any how I want to do this so friends please help me. I'm using version:'1.2-devel'. Also I have other query,I want to know that,when frame changes,it will send request all the time to server  which cause to slow the speed,show I want to preload all images and plugin takes images from cache.Please Help me to solve this

**Comment by pisi** [comment]
This error can be coming from anywhere. I would need to see this in action to help more.

I may be wrong, but generally, I'm afraid that's far too many images, some ten times more than Reel is designed to handle. Reel does preload all those, so that means 720 hidden image tags need to be created in the process in order to serve them from cache. I am not that sure a browser is capable of handling this many images at once. I've seen pages with hundreds, if not thousands images on one HTML page, so that indeed works. But such pages alone are so heavy and not really usable even without a script trying to rapidly switch between them..

**Comment by sagarquad** [comment]
thnx for replying,but now i want to try,something like, when i click stop button image rotation will stop.after when i click start it will start from continuous frame.Also I want to ask you  how to stop auto rotating frame,in my case when i click on img it stoped,but after sometime it will start rotating.Also I have two buttons for next and previous so please provide some code,I read your documentation but I didn't success to implement it

**Comment by pisi** [comment]
There are `"play"`, `"stop"` and `"pause"` events ([docs](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#Playback-Control-Events)) available for you to `.trigger()` them to control the animation.

Then, Reel is interacted with by dragging. When you clicked, you basically initiated a drag and in that case animation pauses and waits for end of the interaction plus the time specified with [`timeout`](http://jquery.vostrel.net/reel#timeout) option. ([docs](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#Animation)) That's why it stopped. You can disable the drag interaction entirely if you want with [`draggable`](http://jquery.vostrel.net/reel#draggable) option.

Reel already contains next and previous actions. Just click on either left or right half of the image. To do this with your own external control, you want to `.trigger()` `"stepLeft"` or `"stepRight"` events ([docs](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#Click-Stepping-Events)).

**Comment by pisi** [comment]
As much I want to have issue resolutions verified, I want such long resolved ones out of the way. Verification still welcome tho!
