### ISSUE TITLE
Click on image to step

### ISSUE THREAD

**Issue by pablosbrain** [pisi/Reel#20]
Feature Request: Click either half of an image to go to the next or previous frame

Similar to the navigation in some lightbox image gallery displays, make it possible to click once without dragging on either side of the image to step through the frames.

**Comment by pisi** [comment]
Nice one, Pablo! Interesting suggestion, indeed. Thank you very much for it. It fits very nicely my future vision of Reel. I also expect some UI elements like arrow buttons sticked to both left and right edges of the image to visually support such possibility. Stay tuned for future versions. It probably won't be inside the upcomming patch release 1.1.1, but it certainly will be in 1.2.

**Comment by pisi** [comment]
The implemented a solution for this feature request, that has two distinct aspects:
1. As @pablosbrain requested the entire image area is now clickable and depending on the click position relative to the image center, it triggers either `"stepLeft"` or `"stepRight"` event. This is enabled by default and can be disabled by setting  new option `steppable` to **false**.
2. And that brings us to the new events - `"stepLeft"` and `"stepRight"`. These two when `.trigger()`ed they advance Reel instance one frame left or right. Events are available even when `steppable: false`.

**Comment by pisi** [comment]
The code was merged into [development](/pisi/Reel/tree/development) branch

**Comment by pisi** [comment]
Gregory Stewart reported: "one thing I noticed with the stepping is that when I use it with the option to reverse the direction of my slides ({cw : true}) the built-in stepping ignores it and uses the default direction."

**Comment by pisi** [comment]
I'm a bit baffled by Greg's report, because as far as I tested it, if setup right, if clicking the left half causes a default counterclockwise motion and vise versa. If `cw: true` the reaction is the same - left click for counter-clockwise. So it works just as expected.

I think it may be just a matter of [`cw`](http://bit.ly/reeljs#cw) option misuse. The [`cw`](http://bit.ly/reeljs#cw) option is not for reversing the direction. It is there to tell Reel in what manner you have your shots organized, how (in which direction) you took your pictures. You can not deliberatly change this value as it is either this or that depending on the images. Reel assumes a counter-clockwise order of the frames. Rule of the thumb is, that when you setup your Reel and while dragging, the object or the scene does not follow the mouse when dragged, you need to use the `cw` option to correct Reel's assumption.
