### ISSUE TITLE
Canvas Support

### ISSUE THREAD

**Issue by sagarquad** [pisi/Reel#200]
Thanks for providing wonderful plugin,I want to know that canvas is supported by it or not?
If supported then how can i achieve this.please provide demo, cause i'm not good at js,so please.So if I show in inspect element their should be canvas instead of all images tag used bt plugin.

**Comment by pisi** [comment]
Canvas is not supported. Reel essentially uses just one single `<img>` tag to achieve the effect. The other image tags inside the wrapper are invisible to user are there only to cache individual frames.

You can only use canvas in [annotations `html`](/pisi/Reel/wiki/Annotations).

I do plan some minor interface elements be drawn with canvas instead of external assets. But otherwise I have no plans to support canvas - doesn't make a lot of sense to me so far. I may one day tho ;)

**Comment by sagarquad** [comment]
thanks for your quick response,I having a issue which is not big,but howeverv I can't solve it.When I drag mouse right side my frames goes left side and vice-versa. I am using multi row sequence.The problem only occuring with horizontal directions not with verticle.Also frame are flickering(blinking) in opera version : 12.15.

**Comment by pisi** [comment]
Use [`cw`](http://jquery.vostrel.net/reel#cw) option to tell Reel your images are horizontally shot in opposite order.

**Comment by pisi** [comment]
Also, if your images flicker they most likely are either too big (dimensions-wise) or their quantity is too high.

**Comment by sagarquad** [comment]
Is there any way to action with too high quantity and too big size image?

**Comment by pisi** [comment]
You can do either one or the other, but both together not much... Such cases pretty much come down to amount of CPU power available on each of the individual device you expect your core audience to be using. It's a fine balancing act, frankly.
