### ISSUE TITLE
Pausing at annotation

### ISSUE THREAD

**Issue by tinyearth** [pisi/Reel#203]
I'm trying to use Reel as demonstrated in the "panorama-non-looping-stitched" example. Is there a way to define a pause when the panorama auto plays and reaches an annotation?

I couldn't find this is in the documentation.

**Comment by pisi** [comment]
Reel doesn't support pausing on annotations out of the box, sorry.

You should be however able to bind to the `frameChange` event, in the handler check each individual annotation dimensions and position and eventually trigger `pause` event by yourself.

``` js
$('#image').bind('frameChange', function( e ){
  $('#image').siblings('.reel-annotation').each( function( ix, annotation ){
    var
      position = parseInt( $(annotation).css('left') ),
      width = parseInt( $(annotation).css('width') ),
      space = parseInt( $('#image').css('width') )

    if ( position > 0 && position + width < space ){
      $('#image').trigger('pause');
    }
  });
});
```

If you run this piece of code in the developers console of any running [example here](http://test.vostrel.cz/jquery.reel/example/) (actually, only those marked contain annotations to test), you will see how it works.

This will pause on every annotation once on every frame it is completely in the view. However you will still need to add some logic to prevent double-pausing on annotations when they travel cross the view. Because now when it pauses and then resumes to next frame and the annotation still fits, it will pause again.

**Comment by tinyearth** [comment]
Petr, that is super helpful—thank you so much!

**Comment by pisi** [comment]
My pleasure!

**Comment by tinyearth** [comment]
Petr, I've sent you an email. Can you check and reply when you get a chance? Thanks in advance!

**Comment by tinyearth** [comment]
Petr, I replied to you, but I'm not sure you saw it or if it got buried in your other emails. The message is about paying (donations) for Reel. Could you respond and let me know if it's something that can be done? Because if not, I need to figure out an alternive very soon. Either way, let me know please. Thanks!

**Comment by pisi** [comment]
Sorry ^^ Replied.
