### ISSUE TITLE
how to use steppable option

### ISSUE THREAD

**Issue by mirzatalat** [pisi/Reel#216]

**Comment by pisi** [comment]
The [`steppable` option](http://jquery.vostrel.net/reel#steppable) is easy and it is not matter of usage, but a mere enable/disable. And it is enabled by default.

When this option is enabled, Reel adds an additional click interaction alternative. Clicks on either halves of the image will advance the Reel by one frame in respective direction. Internally it triggers `stepLeft` and `stepRight` events, which can be called externally by custom controls.

Disabling this option makes Reel to ignore such clicks. However the events can still be used.

**Comment by mirzatalat** [comment]
Also wanted to ask one thing, If I wan to use this plugin on button click ,how would that be possible.Like rotating the object(sequence of images) to left on pressing left button and right on presssing right button.Can you please help me with the solution.

**Comment by pisi** [comment]
This is quite out of scope of the original ticket, but hey...

Playing an instance on click is as easy as:

``` js
$("#my_reel").click( function(){
    $("#my_reel").trigger('play', 0.5);
});
```

where `0.5` is the new speed. Playing in other direction is about passing negative steep `-0.5`. Be sure to set `steppable: false` to disable the stepping, which would otherwise interfere visually.

Using right mouse button for whatever purpose is still against UI best practices, but if you really do want to go against the flow, I'm sure you will find your solution on [stackoverflow.com](http://stackoverflow.com) for example.
