### ISSUE TITLE
106 Frames in 1 row throws error

### ISSUE THREAD

**Issue by jacobdubail** [pisi/Reel#235]
I modified one of your jsfiddles to make sure I wasn't crazy: http://jsfiddle.net/jmQq5/37/

If I remove the "rows" option, the script runs, but I don't get all 106 frames. I see the same ~20 frames repeated.  

My sprite is 1 long row that was put together by the python script you reference in your faq.

Any idea what I broke?

Thanks,
Jacob

**Comment by pisi** [comment]
Hi,

you broke nothing, Jakob! It's just that `rows` are not for you in case you have just one row. What fails you is the default footage (frame length of sprite "line"), which is `6`. You need to set `footage: 106` to match your sprite line footage of 106 frames.

``` js
$("#XY").reel({
  frames: 106,
  footage: 106,
  ... // and the rest of options
})
```

I updated your fiddle - http://jsfiddle.net/jmQq5/38/

But you sure did have tapped something, because **`rows: 1` should be the same as no rows at all**. Need to fix that.

**Comment by jacobdubail** [comment]
Thank you!  I thought I had made the sprite too wide for the browser to process since the background-position supposedly only handles up to ~32,000px, if I'm not mistaken.

I appreciate your response!

-Jacob

**Comment by pisi** [comment]
Pleasure :)
