### ISSUE TITLE
loops parameter doesn't work on multi-row sequences

### ISSUE THREAD

**Issue by ov** [pisi/Reel#244]
Here is a small sample: http://jsfiddle.net/4hmYv/ try to rotate it to the left and to the right. Rotation stops at the first frame when I dragging to the left, but I can rotate infinitely to the right and after the very last frame in the row it shows the very first one.

Everything works fine if you remove the `data-rows` attribute, so the sequence becomes single-row.

Things getting worse, if you add `data-rowlock="true"`, as then it jumps to the bottom rows, while you rotating, but doesn't allow you to go back, so you end up at the very last row.

Here you can see the same issue directly in the samples: http://test.vostrel.net/jquery.reel/example/panorama-multi-row-stitched/

**Comment by pisi** [comment]
Keen eye, mister!

**Comment by ov** [comment]
cheers :)
would be also nice to have the same loop/noloop and cw/ccw functionality for vertical rotation. seems not that difficult.

**Comment by pisi** [comment]
Turned out I cut off a seemingly obsolete code, which (in a modified form) is still needed for the multi-row non-looping movies. Please employ your keen eye again and try out the patched code in [**gh-244-non-looping-multi-rows** branch](/pisi/Reel/tree/gh-244-non-looping-multi-rows) and please let me know how that works for you. Thanks!

About those options for vertical axis. Not really possible in v1.x of the plugin (but I can as well be wrong!, all contribution efforts are welcome). On the paper however these are the features of v2, where both axes will be functionally equal.

**Comment by ov** [comment]
@pisi the branch works well for me. love the fix, it looks crazy :)

thanks for the answer regarding the vertical axis. do you have a list of planned features for v2? I have some ideas, but you haven't replied to my e-mail about a week ago.

**Comment by pisi** [comment]
Great! Thanks for the verification.

Glad you like it :) It is not that crazy. `+!truth` is just a neat way to convert Boolean `truth` into reversed integer (`true` to `0` and `false` to `1`). Simplified version of line you'd otherwise write as `truth ? 0 : 1` for example.

As to planned features. The "paper" is in my head so far. I plan roughly the same features, but with a better options interface. Mainly I have an idea how to add alternative dimensions to image layers, which will will result in all layers being functionally equal with animation, inertia and all such options applicable to any of these layers. One such added dimension can be vertical, zoom, sub animation or what ever.

Sorry about your e-mail - you're in the queue, I'll get to yours eventually. Feel free to open up a ticket with your ideas for further discussion.

**Comment by ov** [comment]
got it, thanks

**Comment by pisi** [comment]
Merged and awaiting release. Until then, please use CDN's http://code.vostrel.cz/jquery.reel-edge.js or code from the [**development** branch](/pisi/Reel/tree/development).
