### ISSUE TITLE
HTTPS and CDN

### ISSUE THREAD

**Issue by lozcalver** [pisi/Reel#249]
Using the `http://code.vostrel.net/` CDN results in content policy issues in numerous browsers for websites running over HTTPS. Might be worth mentioning in the docs if you don’t intend to support HTTPS for the CDN :)

**Comment by pisi** [comment]
Try linking `//code.vostrel.net/` instead (without the http(s))

**Comment by lozcalver** [comment]
This causes it to attempt to contact `https://code.vostrel.net/`, which it can’t due to an SSL protocol error

**Comment by pisi** [comment]
Ah, I see. Well, on my CDN, which runs on Google, I don't really plan to add the HTTPS, but I'm long considering using cdnjs.com and since they support HTTPS, I now have a strong reason too :)

The only problem I see is that the plugin itself has its `$.reel.cdn` preset to HTTP URL too for fetching cursor image, so that might be provoking a security warning about non-secure content out of the box. We'll see. Will look into this on the weekend.

**Comment by jimaek** [comment]
How about [jsdelivr.com](http://www.jsdelivr.com)?
Full HTTPS support and good uptime http://www.cdnperf.com/

**Comment by pisi** [comment]
That is a very nice one too! Thanks for suggestion :) Their number looks pretty good.

**Comment by lozcalver** [comment]
It's not a major issue - for now I've simply downloaded the assets I need and set the CDN to be a folder on my site :)

**Comment by pisi** [comment]
OK, so I went with jsdelivr for starters. @kinglozzer can you please try to link https://cdn.jsdelivr.net/jquery.reel/1.3.0/jquery.reel.js in your HTTPS page and let me know how it works and if all resources get loaded from therein, especially cursors, since I am using protocol-relative `$.reel.cdn` URL. Thanks.

**Comment by lozcalver** [comment]
@pisi I’ve not yet pushed the code up to our HTTPS server, but running the code locally (over regular HTTP) results in a 404: I think the CDN path is wrong (path includes `/1.3/` instead of `/1.3.0/`).

If I manually specify the CDN:

``` js
$.reel.cdn = '//cdn.jsdelivr.net/jquery.reel/1.3.0/';
```

then it works (again, over HTTP at the moment). If you can update the path I’ll push the code up this afternoon and test :).

Thanks for your help on this.

**Comment by pisi** [comment]
Oh, crap. You're right, I forgot to fix the actual folder name... Please test it with the manual override you made. That would verify the function too.

**Comment by lozcalver** [comment]
Okay, I’ve just tested with the CDN specified as above and it’s working perfectly :+1:.

**Comment by pisi** [comment]
Great! Glad it works. Pushed all major versions and fixed the path's so that the patch is not needed anymore. Be aware the URL now really is just 1.3 (without the last zero). Updates of docs will follow.

**To use the [SSL-enabled HTTPS CDN](http://www.jsdelivr.com/#!jquery.reel) link _one_ of these:**
- **1.3** ([v1.3.0](/pisi/Reel/tree/v1.3.0)) 
  - https://cdn.jsdelivr.net/jquery.reel/1.3/jquery.reel.js
  - https://cdn.jsdelivr.net/jquery.reel/1.3/jquery.reel-bundle.js
  - https://cdn.jsdelivr.net/jquery.reel/1.3/jquery.reel-debug.js
- **1.2** ([v1.2.2](/pisi/Reel/tree/v1.2.1))
  - https://cdn.jsdelivr.net/jquery.reel/1.2/jquery.reel.js
  - https://cdn.jsdelivr.net/jquery.reel/1.2/jquery.reel-bundle.js
  - https://cdn.jsdelivr.net/jquery.reel/1.2/jquery.reel-debug.js
- **1.1** ([v1.1.4](/pisi/Reel/tree/v1.1.4))
  - https://cdn.jsdelivr.net/jquery.reel/1.1/jquery.reel.js
  - https://cdn.jsdelivr.net/jquery.reel/1.1/jquery.reel-bundle.js
  - https://cdn.jsdelivr.net/jquery.reel/1.1/jquery.reel-debug.js
- **1.0** ([v1.0.4](/pisi/Reel/tree/v1.0.4))
  - https://cdn.jsdelivr.net/jquery.reel/1.0/jquery.reel.js
  - https://cdn.jsdelivr.net/jquery.reel/1.0/jquery.reel-bundle.js
  - https://cdn.jsdelivr.net/jquery.reel/1.0/jquery.reel-debug.js

`-bundle` has mouse wheel plugin baked in,
`-debug` is annotated source code.

Enormous thanks to Dmitriy Akulov at [jsDelivr](http://www.jsdelivr.com)
