### ISSUE TITLE
Internet Explorer 8 Iframe Issue

### ISSUE THREAD

**Issue by nezumidesigns** [pisi/Reel#25]
I have created a web page that opens a lightbox window (in this case I used Colorbox).
The pop-up lightbox window shows the Reel animation.

I tested the page using Firefox, Safari, Opera, and Chrome and these worked fine.  When I tested it on Internet Explorer 8 I had a curious result.  When you drag your mouse left and outside the animation frame, the animation turns blue as IE creates a selection box around it as if selecting text on a web page for copying.

This is not really a desirable result for me, so I wondered if anyone knows of a work-around that I could use.  If you have difficulty understanding the problem I have posted an example at:

http://www.new-developments.co.uk/3dviewer/

Click on the link "Click here for 3D view" to open the lightbox viewer, then drag the animation left and outside the box to see the frame turn blue. Make sure you use IE as there is no problem with other browsers.

Thank you in advance for any suggestions.

**Comment by pisi** [comment]
Hi there,

sorry for the inconvenience. So far I nailed your issue down to `IFRAME` being the primary issue in your case. I'm further investigating means to prevent starting of selection when dragging between frames.

Cross fingers! ;)

.pisi

**Comment by pisi** [comment]
Hi again,

I've nailed down the issue with dragging out of the iframe, which was causing to not release the drag. This has been fixed in c4f4d57 in the development branch and works just fine now - the mouse drag is properly released and not causing problems any more.

But when playing with it I've never come across your issue and I suspect incorrect usage of the disableTextSelect plugin may be in place. I noticed you use this plugin inside your `IFRAME`, but not in the containing page (outside) - and that's my best guess. When I use it having it linked inside both documents, it works just fine.

Closing this issue as the fix is already for soon release in 1.1.2, but please feel free to continue with your comments if neccessary.

**Comment by nezumidesigns** [comment]
That's really good news.  Thank you for looking into this and resolving the problem.  I look forward to the new release.

Thanks again.

**Comment by pisi** [comment]
Just to let you know, the Reel 1.1.2, which includes fix for dragging out of an iframe, is out several days now. Please, get it from the [Reel site](http://jquery.vostrel.cz/reel) and try dropping it into your app. I'm sure that when you'll use 1.1.2 in tandem with the disableTextSelect plugin, your issue will be gone.

You can even try the bundle version of Reel from the [CDN](http://github.com/pisi/Reel/wiki/CDN) which has this 3rd party plugin bundled in alongside the latest version of Reel:

```
http://code.vostrel.cz/jquery.reel-bundle.js
```
