### ISSUE TITLE
Custom drag_cursor image?

### ISSUE THREAD

**Issue by marissajmc** [pisi/Reel#45]
Is it possible to use a custom drag_cursor image? I changed the image paths but the new cursor is not appearing (path is correct in Net panel). It's always the failsafe_cursor. (ff3.6 mac)

(I ended up removing the source code that embeds a cursor and set it myself with css).
(NOTE: custom cursors are not supported in ff3.6 mac).

**Comment by pisi** [comment]
Judging by the closed status, it looks like you've figured it out by yourself. In case you did not or for others:

There isn't any special setting or a public way how change the drag cursor in Javascript. But you can do it in CSS very easily. See the [code snippet](http://jsfiddle.net/uCPTY/2/), for example with "move" cursor applied instead of the built-in ones.
