### ISSUE TITLE
Problem with ajax and jquery Reel

### ISSUE THREAD

**Issue by zazoomauro** [pisi/Reel#47]
I have a problem with this plugin.
When I try to use it the first time everything is perfect but when I try to use it later without refreshing the page does not work ...
Anyone know why?

My code:

WEB.REELPAGE.open = function(){
$('#main').load('sneakers.html',function(){
$('.imageReel').reel({
            delay: 0,
            speed: 0.5,
            path: 'img/',
            cw: true,
            images: ['1.png','2.png','3.png','4.png','5.png','6.png','7.png','8.png']
        });
})
};

sneakers.html contains only one image with this attributes class='imageReel' and src='img/sneakers/centennial_mid/element/360/1.png'

**Comment by fazeaction** [comment]
For the moment I dont know why but add this line after line 157. It's working for me:

if($.reel.instances.length>0) remove_instance($.reel.instances.first());

Excerpt:

 on= {
          setup: function(e){
          /*
          - fills up the data storage with values based on options
          - binds to ticker
          */
            if (t.hasClass(klass)) return cleanup.call(e);
            if($.reel.instances.length>0) remove_instance($.reel.instances.first());

**Comment by zazoomauro** [comment]
Works!!!

**Comment by pisi** [comment]
First, **Fazeaction**,

first of all let me thank you very much! It's pretty cool that you literally found the issue here. I long had no clue what might be wrong with the code, but now I think I'm starting to get it, thanks to you. Your solution very clearly uncovers, that the problems experienced are a logical _consequence of not having the instance __properly__ removed_ from the DOM.

Your solution for this is indeed very right and I can not thank you enough for helping out and bumping me on the right track. It unfortunatelly won't do the trick for multiple Reel instances on the page simultaneously. 

**Zazoomauro**,

The `"teardown"` event will come handy in situations like these, where you i.e. dynamically dynamically build (and destroy) instances, like loading one Reel in place of another. It removes the existing DOM node and all its data and event bindings by restoring the original image element Reel was built upon. It performs all necessary cleanup for you, including the call to `remove_instance` for example.

So instead of the proposed Reel modification, putting this:

```
$('.imageReel').trigger('teardown`)
```

just before the `.load` call would be the recommended solution for your code.

Thank you, guys, for cooperating on the solution here on Github :) You both have helped!

**Comment by pisi** [comment]
This issue qualified for frequently asked question and has become part of the [FAQ](/pisi/Reel/wiki/FAQ) wiki page.

**Comment by marissajmc** [comment]
Thanks <b>fazeaction</b>, that new line worked for me when loading a Reel instance with ajax on click.

.trigger('teardown') did not work in this case.
