### ISSUE TITLE
Image quality on iPad

### ISSUE THREAD

**Issue by hat360** [pisi/Reel#54]
Hi, we are looking to fill a full screen on the ipad (768 x 1004 pixels). The functionality works great for us, auto rotates/animates the images and allows us to use hotspot areas over the top.

The problem I have is the complete degradation of the image when using the safari browser on the ipad - safari works fine on the mac with the images showing in perfect clarity.

Are there any settings I can change to improve the image quality ? The object-reel.jpg image is the correct pixel size for what I want (4608 x 1004 px - has 6 frames across).

Any advice would be appreciated.

Thanks

**Comment by CaioMatias** [comment]
Hi, the answer is on Wiki - FAQ:

I’m experiencing weird scaling down of my image on iPhone or iPad. Why’s that?
This is often exhibited by several frames of sprite appear on screen at once.
As a result of iPhoneOS memory limitation imposed on image dimensions, your image sprite gets scaled down to fit in memory. In that case you have several options:

you can make your sprite smaller,
or use sequence of individual frames instead. Unfortunatelly this comes with a penalty of downloading several images instead of just one.

=D

**Comment by marissajmc** [comment]
I had the same sprite image scaling problem on iPhone and iPad, and the solution was to use an array of individual images instead.

**Comment by pisi** [comment]
Hi folks, it is exactly that. It is a known issue described in [FAQ](/pisi/Reel/wiki/FAQ). The advised solution would be to use [`images`](http://jquery.vostrel.cz/reel#images) option and feed it with an Array of filenames/paths to individual frames.
