### ISSUE TITLE
delay not working

### ISSUE THREAD

**Issue by AlphaKilo615** [pisi/Reel#58]
i set the delay to -1 and it still auto plays. I can change it to 15 seconds and it will delay, but the -1 will not stop it. I used the widget from Dreamweaver cs5 and the js file lead me to the site it originated from. If you need to see the code, please let me know and i can post it. Thanks.

**Comment by AlphaKilo615** [comment]
Here is the page by the way: http://www.theadamgrp.com/client-demos/360/zero-g-3602.html

**Comment by AlphaKilo615** [comment]
Ok, i got it working. its kind of glitchy. im not sure if its me. It skips some frames when i rotate it. here's the page reference: http://www.theadamgrp.com/test/reel/object5.html

This time i created image sprites, since the stacked one wasnt playing well with me.

Here's the reel sprite image: http://www.theadamgrp.com/test/reel/zerog/zerog-reel.jpg

Does anyone see the frames are skipping? Any help would be awesome! thanks.

**Comment by AlphaKilo615** [comment]
ALSO! Here's a video =] http://screencast.com/t/6cJ7LNfZ

**Comment by doa4real** [comment]
you forgot - footage: 7
Number of frames per line.... - that should do the trick.

btw you sould use 36 sprites for a smooth reel.

**Comment by pisi** [comment]
I agree with doa4real, the footage is crucial and that's why it is jumping. Default `footage` option value is 6, but your sprite has 7. AlphaKilo645, just add `footage: 7` to your list of options and you should be set.

Also the autoplay happens with non-zero `speed` option. The `delay` only delays the start, but has no power to stop the animation if the `speed` is set.

Hope this helps,

.pisi
