### ISSUE TITLE
IE 8 Failure

### ISSUE THREAD

**Issue by pfleming** [pisi/Reel#71]
Hi

I have uploaded the test scripts to our server and they do not seem to work in IE 8. All other browsers are fine.

Is there a MIME type that is required or any known issue that would cause this as your test site works as it should.

http://ahume.co.uk/360%20test/test/sampler.html -  does not work

http://jquery.vostrel.cz/reel - fine

Any help would be much appreciated.

Thanks

Pete

**Comment by pisi** [comment]
Hi Pete,

by inspecting the resources loaded, i came to conclusion, that there's no mistake on your server's side. It's the jQuery CDN that has an outage of some sort (I guess they are upgrading the CDN or something) and http://code.jquery.com/jquery-latest.min.js is therefore offline.

Reel homepage uses http://code.jquery.com/jquery-1.6.min.js, which you most probably already have in your browser's cache (at least I do) and that's why it still works despite the CDN actually down.

You can try to edit the `sample.html` and use `1.6` instead of the `latest`. Or wait till the CDN is up again ;)

**Comment by pisi** [comment]
Btw. the official jQuery CDN is back up and the uploaded test scripts at your server work just fine.

**Comment by pisi** [comment]
Please be aware that Reel 1.1.x has been patched to work just right with jQuery 1.7 in IE - fixes init-time error (like yours) and wheel issues. Released as [Reel 1.1.4](/pisi/Reel/tree/v1.1.4).

Note, that you must also upgrade your copy of the mousewheel plug-in with the included version [3.0.6](/brandonaaron/jquery-mousewheel/tree/3.0.6). The one shipped with Reel 1.1.3 (mousewheel 3.0.4) was also jQuery 1.7 incompatible.
