### ISSUE TITLE
jquery 1.7 issue

### ISSUE THREAD

**Issue by cindreta** [pisi/Reel#74]
So this maybe just my issue but still it happend when the switch to the new version of jquery occured.

Basicly in Chrome Dev tools it says something like this:

Uncaught TypeError: Property 'loaded' of object #<HTMLImageElement> is not a function
f.event.triggerjquery.min.js:3
f.fn.extend.triggerjquery.min.js:3
e.extend.eachjquery.min.js:2
e.fn.e.eachjquery.min.js:2
f.fn.extend.triggerjquery.min.js:3
update_preloaderg=js:155  ===========> THE FILE CONTAING JQUERY REEL
f.event.dispatchjquery.min.js:3
f.event.add.h.handle.i

Jquery version is 1.7, jquery reel versions i tried is 1.1.3 (lates stable) and the development version. is this my fault or?

**Comment by pisi** [comment]
As far as I'm concerned right now, Reel is working and performing even one notch better in jQuery 1.7. The tests are passing and subjective feeling is a bit better, snappier especially on mobile devices - great work on cutting the event wiring of jQuery team! Have been testing against 1.7 since its beta 2.

This applies for the current development branch. I haven't tested 1.1.3 against jQuery 1.7, shame on me... But 1.7 beta 2 went fine ;)

But this definitely fails at `.trigger()`ing Reel's `"loaded"` event, which in the source does just one thing - the preloader. It is a one-time event triggered by the preloader when all images needed for the show are loaded. In the code it is used as a string argument for standard `.trigger()`. Don't know really. Maybe something tries to tickle it the wrong way (and modifying the preloader maybe? Just guessin' and judging from the filename).

**Comment by cindreta** [comment]
well no it seems to be fixed, i used the latest development version and everything is ok. thanks man.

**Comment by pisi** [comment]
Very well :)

**Comment by pisi** [comment]
Please be aware that Reel 1.1.x has been patched to work just right with jQuery 1.7 in IE - fixes init-time error (like yours) and wheel issues. Released as [Reel 1.1.4](/pisi/Reel/tree/v1.1.4).

Note, that you must also upgrade your copy of the mousewheel plug-in with the included version [3.0.6](/brandonaaron/jquery-mousewheel/tree/3.0.6). The one shipped with Reel 1.1.3 (mousewheel 3.0.4) was also jQuery 1.7 incompatible.
