### ISSUE TITLE
Custom Graph function can't do circular drag

### ISSUE THREAD

**Issue by Barnabas** [pisi/Reel#82]
While user testing this Reel plugin, we noticed that some users tried to grab the actual item in the picture and drag it around in a circular motion. This works as long as they are on the top half of the image, but the direction unexpectedly reverses as soon as they cross over to the bottom half.

To address this, I wanted to extend this plugin with a custom graph function, so that instead of using a fraction of the X position, I'd return a fraction of degrees around the center point, allowing a circular drag motion. However, the graph function only takes a single dimension, X or Y depending on current orientation. So, can/should the graph function have a 2-dimensional point parameter? Or should Reel naively understand the degrees from center? Or, have I misunderstood the graph function?

**Comment by pisi** [comment]
Hey, I'm very excited to see you've user tested Reel. First usability knowledge is coming in. How cool is that :) Thank you very much for sharing it with me!

Circular motion you say - sounds fairly reasonable and in some cases more intuitive than just linear drag. And you are right the single-axisness of graph functions make it pretty hard to implement. So from now on the graph function will receive the other axis as the last parameter, so that your attempts are possible.

Good luck! Looking forward to a pull request ;)
