### ISSUE TITLE
turntable flicker on opera for large images.

### ISSUE THREAD

**Issue by pelister** [pisi/Reel#91]
Hi Petr,

Today I found a strange behavior with latest alpha1 release of reel. Testing with latest development branch.

In case of Opera when reel is created with large images (I used images at 800x600 px (total 400 images)) flickering happens for each image transition. and the latest mouse cursor does not appear in opera.

In case of IE 8 the vertical indicator that appears for multirow reel is not appearing.

**Comment by pisi** [comment]
OK, thanks for the observations. Opera doesn't accept `cursor` CSS property and I don't know about a workaround. I'll take a better look on the rest. Can you maybe made your files accessible? I have no such big samples available.

**Comment by pelister** [comment]
here is the archive containing all the files I used for the test.

Edit: LINK REMOVED

**Comment by pisi** [comment]
@pelister, thanks for the archive, it really helped to debug it faster. I however am not able to reproduce the flickering issue on my machine (Opera 10.10 on MacOS 10.6.8).

All I was able to get is a brief flash of the black background just before the Reel gets initialized. The thing there is that the very first image you have in the `<img>` `src` attribute doesn't have a chance to load, because Reel is initialized during it loading. Therefore it switches to Reel frames from nothing. You want to make sure the image is loaded (and visible) before you initialize.

I wrapped your `.reel()` call first in `.load()` and the black flash is gone:

``` js
$(window).load(function(){
    // your `.reel()` call
})
```

As far as the flickering goes, I'll have to do some guess work and I'd bet on caching. For Reel it is crucial that the server serves proper caching headers. Simply said, it has to return HTTP code 200 (OK) plus the image for the first time the image is requested and just code 304 (Not Modified) with no image for all following calls. If this fails, browser will try to fetch a fresh copy of each frame each time it is requested. And when animated, it may not get the whole response before the next frame is requested. When loading your files from local disk with `file://` protocol, you always get 200 and images are reloaded all over again and again and again. Can you verify this is not case, so I can eliminate this eventuality?

**Comment by pisi** [comment]
And btw. the model is just awesome! Excellent work. I keep on playing with the landing gear ;]

**Comment by pelister** [comment]
I hope its problem with the cache, though I load it from local disk, it happens only on opera 11.60  - the version I use.

other browsers work fine. As you said images are loaded with file://localhost/M:/.... protocol. and thanks for the compliments on the model.
