### ISSUE TITLE
Swapping images and resetting Reel within a page

### ISSUE THREAD

**Issue by williammincy** [pisi/Reel#96]
Hi, I'm working with your plugin (thanks, BTW, for making such a cool project available on Github) and am hoping you can share some insight on how you were able to execute the image switching and plugin resetting you achieved in your example page (http://test.vostrel.cz/jquery.reel/test/sampler.html).

From what I can tell you're storing the values in the page but I can't quite find where you're making the call to do the swap and reset the plugin. Could you tell us a bit about how you achieved this within the page? 

Thanks in advance, 
 william.mincy

**Comment by pisi** [comment]
Basically there is a `<ul class="groups">` in the body, where the visible part of `<li>`s is used for "navigation" segment at the top (the links). Besides it there are some invisible segments including three `<xmp>` tags representing HTML, CSS and JS example code you then get to see on the page under the example image.

When the example is rendered all three segments get evaluated and used to prepare and construct a call to `.reel()` function. Basically it takes `#the_one #image` image tag, sets its `src` to URL from the HTML segment and applies dimensions from the CSS segment. Then options object from JS segment is used as a single parameter to the `.reel()` call.

Please note, that the URL runs the development version of the code, so some bits may differ from the 1.1.3. Especially the need to `.trigger("teardown")` event first in order to allow for re-use of the stage.

The plan is to allow easy re-use by mere re-calling `.reel()` on the node again without any other constrains.

**Comment by pisi** [comment]
You may also be interested in the revised [`examples/`](/pisi/Reel/tree/v1.2alpha/example) folder in the [1.2alpha](/pisi/Reel/tree/v1.2alpha) distribution, where my aim was to extract the understandable essence of what it takes to get reeling, which to my mind is much more clean and concise compared to the previous.

**Comment by williammincy** [comment]
You are right, the 1.2alpha is much clearer, and the `unreel` function is very, very invaluable. Thanks for the response and for the really great plugin.
